### ISSUE TITLE
Problème avec installation de Jeedom (PHP)

### ISSUE THREAD

**Issue by MarcHambuch** [PuNiSHeR374/Jeedom#3]
Bonjour,

jai un problème lors de installation de Jeedom.

L´installation s´arrete a cet endroit sans installer Jeedom

Merci

Jai un paquet PHP 5.6 actif sur mon ds215+ / dsm6

merci
---------------

/tmp/jeedom.zip     100%[=====================>]  27.12M   471KB/s   in 60s     
                                                                                
2016-08-05 10:16:20 (464 KB/s) - /tmp/jeedom.zip saved [28435546/28435546]      
                                                                                
Restarting periodic command scheduler: cronStopping periodic command scheduler: 
cron.                                                                           
Starting periodic command scheduler: cron.                                      
Starting web server: apache2 failed!                                            
The apache2 configtest failed. ... (warning).                                   
Output of config test was:                                                      
[Fri Aug 05 10:16:27.619889 2016] [:crit] [pid 5194:tid 1995960320] Apache is ru
nning a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You
 need to recompile PHP.                                                         
AH00013: Pre-configuration failed                                               
Action 'configtest' failed.                                                     
The Apache error log may have more information.                                 
root@DS215:/tmp# N                                                              
bash: N: command not found

**Comment by megastorage** [comment]
Bonjour,

Nous gérons l'installation de jeedom seulement sous chroot.

Pour les problèmes d'installation de jeedom directement en ssh sur le dsm, merci de voir avec le support jeedom.

Stéphane.
